{% set name = "bio-embeddings-cpcprot" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bio_embeddings_CPCProt-{{ version }}.tar.gz
  sha256: 046a8699ef771738c482a04459c2b99f59b22e71378d1ebb5e1a083952a5d4b3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 11

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry >=1.1.0
  run:
    - tape_proteins >=0.4
    - python-lmdb >=1.0
    - numpy >=1.19
    - python >={{ python_min }}
    - scipy >=1.5
    - pytorch >=1.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - CPCProt

about:
  home: https://pypi.org/project/bio-embeddings-CPCProt/
  summary: Parameter-efficient pretrained model for obtaining protein embeddings.
  license_file: LICENSE
  license: MIT

extra:
  recipe-maintainers:
    - hadim
